### ISSUE TITLE
Error when trying to compile

### ISSUE THREAD

**Issue by pmitchev** [moneroexamples/transactions-export#1]
I got the following error when I try do compile. I used the latest Monero version. Ubuntu 16.04, i installed the dependencies from here:
https://github.com/moneroexamples/compile-monero-09-on-ubuntu-16-04

> [ 50%] Built target myxrm
> [ 80%] Built target myext
> [ 90%] Linking CXX executable xmr2csv
> /usr/bin/ld: task_region.cpp.o: plugin needed to handle lto object
> /usr/bin/ld: thread_group.cpp.o: plugin needed to handle lto object
> /tmp/ccPqgmHd.ltrans21.ltrans.o: In function `rct::verRctSimple(rct::rctSig const&)':
> <artificial>:(.text+0x2cbc): undefined reference to `tools::thread_group::optimal_with_max(unsigned long)'
> <artificial>:(.text+0x2ccb): undefined reference to `tools::thread_group::thread_group(unsigned long)'
> <artificial>:(.text+0x2ebf): undefined reference to `tools::task_region_handle::create_state()'
> <artificial>:(.text+0x2f88): undefined reference to `tools::thread_group::data::dispatch(std::function<void ()>)'
> <artificial>:(.text+0x2fec): undefined reference to `tools::task_region_handle::state::mark_completed(unsigned int)'
> <artificial>:(.text+0x3092): undefined reference to `tools::task_region_handle::do_wait()'
> <artificial>:(.text+0x30a3): undefined reference to `tools::task_region_handle::state::abort()'
> <artificial>:(.text+0x30b6): undefined reference to `tools::task_region_handle::state::wait(tools::thread_group&)'
> <artificial>:(.text+0x3664): undefined reference to `tools::task_region_handle::create_state()'
> <artificial>:(.text+0x3748): undefined reference to `tools::thread_group::data::dispatch(std::function<void ()>)'
> <artificial>:(.text+0x37bc): undefined reference to `tools::task_region_handle::state::mark_completed(unsigned int)'
> <artificial>:(.text+0x3902): undefined reference to `tools::task_region_handle::do_wait()'
> <artificial>:(.text+0x3913): undefined reference to `tools::task_region_handle::state::abort()'
> <artificial>:(.text+0x3926): undefined reference to `tools::task_region_handle::state::wait(tools::thread_group&)'
> <artificial>:(.text+0x3d0e): undefined reference to `tools::thread_group::data::~data()'
> <artificial>:(.text+0x3d7e): undefined reference to `tools::thread_group::data::~data()'
> /tmp/ccPqgmHd.ltrans21.ltrans.o: In function `rct::verRct(rct::rctSig const&)':
> <artificial>:(.text+0x4f55): undefined reference to `tools::thread_group::optimal_with_max(unsigned long)'
> <artificial>:(.text+0x4f6e): undefined reference to `tools::thread_group::thread_group(unsigned long)'
> <artificial>:(.text+0x50bf): undefined reference to `tools::task_region_handle::create_state()'
> <artificial>:(.text+0x5188): undefined reference to `tools::thread_group::data::dispatch(std::function<void ()>)'
> <artificial>:(.text+0x51ec): undefined reference to `tools::task_region_handle::state::mark_completed(unsigned int)'
> <artificial>:(.text+0x5292): undefined reference to `tools::task_region_handle::do_wait()'
> <artificial>:(.text+0x52a3): undefined reference to `tools::task_region_handle::state::abort()'
> <artificial>:(.text+0x52b6): undefined reference to `tools::task_region_handle::state::wait(tools::thread_group&)'
> <artificial>:(.text+0x56c4): undefined reference to `tools::thread_group::data::~data()'
> <artificial>:(.text+0x5737): undefined reference to `tools::thread_group::data::~data()'
> /tmp/ccPqgmHd.ltrans25.ltrans.o: In function `std::_Function_handler<void (), tools::task_region_handle::wrapper<rct::verRct(rct::rctSig const&)::{lambda(tools::task_region_handle&)#1}::operator()(tools::task_region_handle&) const::{lambda()#1}> >::_M_invoke(std::_Any_data const&) [clone .lto_priv.910]':
> <artificial>:(.text+0x2e2): undefined reference to `tools::task_region_handle::state::mark_completed(unsigned int)'
> <artificial>:(.text+0x301): undefined reference to `tools::task_region_handle::state::mark_completed(unsigned int)'
> /tmp/ccPqgmHd.ltrans25.ltrans.o: In function `std::_Function_handler<void (), tools::task_region_handle::wrapper<rct::verRctSimple(rct::rctSig const&)::{lambda(tools::task_region_handle&)#1}::operator()(tools::task_region_handle&) const::{lambda()#1}> >::_M_invoke(std::_Any_data const&) [clone .lto_priv.908]':
> <artificial>:(.text+0x352): undefined reference to `tools::task_region_handle::state::mark_completed(unsigned int)'
> <artificial>:(.text+0x371): undefined reference to `tools::task_region_handle::state::mark_completed(unsigned int)'
> /tmp/ccPqgmHd.ltrans25.ltrans.o: In function `std::_Function_handler<void (), tools::task_region_handle::wrapper<rct::verRctSimple(rct::rctSig const&)::{lambda(tools::task_region_handle&)#2}::operator()(tools::task_region_handle&) const::{lambda()#1}> >::_M_invoke(std::_Any_data const&) [clone .lto_priv.905]':
> <artificial>:(.text+0x40f0): undefined reference to `tools::task_region_handle::state::mark_completed(unsigned int)'
> /tmp/ccPqgmHd.ltrans29.ltrans.o: In function `tools::task_region_handle::~task_region_handle() [clone .lto_priv.907]':
> <artificial>:(.text.unlikely+0xd): undefined reference to `tools::task_region_handle::state::abort()'
> <artificial>:(.text.unlikely+0x19): undefined reference to `tools::task_region_handle::state::wait(tools::thread_group&)'
> collect2: error: ld returned 1 exit status
> CMakeFiles/xmr2csv.dir/build.make:121: recipe for target 'xmr2csv' failed
> make[2]: *** [xmr2csv] Error 1
> CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/xmr2csv.dir/all' failed
> make[1]: *** [CMakeFiles/xmr2csv.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by moneroexamples** [comment]
Thanks. Just fixed that. Please try now.

Also note, that this functionality has been more or less integrated into [the onion explorer](https://github.com/moneroexamples/onion-monero-blockchain-explorer) in outputs file viewer. The explorer is currently more update to date that this, so please let me know if something else does not work in transaction exporter.

**Comment by pmitchev** [comment]
works now 👍 thank you
