### ISSUE TITLE
Wrong public key found in Example 2, or just my misunderstanding?

### ISSUE THREAD

**Issue by alvinwng** [moneroexamples/transactions-export#13]
I tried to run Example 2 (Monerujo project donation address) and got the first 3 results:
```
Analysing block 01381000/01491188 - date 2017-08-20 21:38:09
 - found 01 outputs in block 01381095 (2017-08-21 01:24:21) - writing to the csv
 - found output as ring member: 5, <f204a2183723de690f216e2f2707cd668f479761e43d781c824a03e98eaf777a>, tx hash: <b6d7a7790104b8ba7891e053b5457e7cf755d58ff87b109bc0edd70c9aa59c8b>
Analysing block 01382000/01491188 - date 2017-08-22 07:48:17
 - found output as ring member: 5, <f204a2183723de690f216e2f2707cd668f479761e43d781c824a03e98eaf777a>, tx hash: <4b80968e8c0344678cc3baca2dd89ce09ef013fd5cb16fb7a58248f948f75c5d>
Analysing block 01383000/01491188 - date 2017-08-23 15:29:58
Analysing block 01384000/01491188 - date 2017-08-25 01:51:44
Analysing block 01385000/01491188 - date 2017-08-26 09:23:44
 - found output as ring member: 3, <f204a2183723de690f216e2f2707cd668f479761e43d781c824a03e98eaf777a>, tx hash: <b53f74bd71a29fcb4ed82cc9b41021a5b672e4f4a35a25b82baed155a0ab6b8e>
```
The program claimed to have found public key `f204a2183723de690f216e2f2707cd668f479761e43d781c824a03e98eaf777a` used as a ring member, but upon inspecting the 3 transactions, the public key used was `99685a6a7449697b5a0e2129c6d6ce5a2249784cb3c058d826d9b7cadad795af`. Wouldn't the result be incorrect, or there is something about the protocol that I don't understand? I thought the public key reported by the program has to appear somewhere in the transactions. Thanks for your clarification.

**Comment by moneroexamples** [comment]
Looking at the three txs:

- https://xmrchain.net/tx/b6d7a7790104b8ba7891e053b5457e7cf755d58ff87b109bc0edd70c9aa59c8b/1
- https://xmrchain.net/tx/4b80968e8c0344678cc3baca2dd89ce09ef013fd5cb16fb7a58248f948f75c5d/1
- https://xmrchain.net/tx/b53f74bd71a29fcb4ed82cc9b41021a5b672e4f4a35a25b82baed155a0ab6b8e/1

a quick regular browser search (Ctrl+F) finds the `f204a2183723de690f216e2f2707cd668f479761e43d781c824a03e98eaf777a` in each of these transactions as ring members.

How did you check that this is wrong? I know that `https://moneroblocks.info/` shows different ring members than xmrchain and that public key you found appears there. So the question is which one is correct? It would be interesting to know your method of validating that the public key you found is the correct one. I think xmrchain (the onion explorer) is correct, as I can estimate correctly my speedings using the ring members it provides.  But then, there's always a possibility that there is some strange bug with the onion explorer, and it shows wrong ring members.

**Comment by alvinwng** [comment]
Thanks for pointing out that [https://moneroblocks.info/](https://moneroblocks.info/) shows different ring members. I checked on [https://moneroexplorer.com/](https://moneroexplorer.com/) and it gave the same results as [https://xmrchain.net/](https://xmrchain.net/). Since the code also looks correct, I think it can be concluded that [https://moneroblocks.info/](https://moneroblocks.info/) is wrong for some strange reason. Without this information, I would still doubt if I understand the protocol correctly. Thanks a lot.

**Comment by moneroexamples** [comment]
https://moneroexplorer.com/ is based on the onoin blockchain explorer (https://github.com/moneroexamples/onion-monero-blockchain-explorer), just like xmrchain is. Thus they can share same bugs. 

I contacted https://moneroblocks.info/ regarding the differences in ring members to rectify this discrepancy between the explores.

**Comment by oerpli** [comment]
Sorry for chiming in late, but are there any updates on this issue?
I've seen [this somewhat recent commit](https://github.com/moneroexamples/transactions-export/commit/b4cbfc996ddb69cb80f46e32e88963d73bc02252) and wondered, whether it is related to the issue described here or if it is a problem from moneroblocks.info

Kind regards

**Comment by moneroexamples** [comment]
No info from https://moneroblocks.info/. The commit you refer was to fix stagenet.  

`transactions-export` works fine. Had no new issues about any incorrectly reported public keys.
