### ISSUE TITLE
Identify RingCT transactions

### ISSUE THREAD

**Issue by oerpli** [moneroexamples/transactions-export#15]
Hello!
Assuming that I've exported the whole blockchain data as CSV - how could I correctly identify all RingCT transactions without false positives?

**Comment by moneroexamples** [comment]
I added tx version to the output csv. tx version 1 is pre-ringct, tx version 2 is ringct. Example command execution from block 1526060, analyze 1000 blocks and scan all outputs
```
./xmr2csv -t 1526060 -n 1000 --all-outputs
```
Result by defult should be avaliable in  xmr_report.csv file.

**Comment by oerpli** [comment]
Thanks a lot!

**Comment by oerpli** [comment]
A quick heads up:
Some coinbase transactions have `tx_version = 2` but I'm not sure whether they are real RingCTs (i.e.: their amounts are visible, [Example](https://moneroblocks.info/search/33b5de4584afb1286cd629eb85d536c81f43ebdfe39f8c5f401568a1326fae5c)).

I think this explains it:
https://monero.stackexchange.com/questions/3348/what-are-3-types-of-ring-ct-transactions

**Comment by moneroexamples** [comment]
coinbase tx are special case (type 0) of ringct txs. There are 3 types of ringct txs as explained in the link you found.
