### ISSUE TITLE
It needs to be re-sync after using xmr2csv on testnet

### ISSUE THREAD

**Issue by heojae91** [moneroexamples/transactions-export#16]
Hi,
I'm on working in testnet to examine how my transaction happens.

I tested ```./xmr2csv -t 1130000 -n 1000 --all-outputs --testnet``` to see every results from block height 1130000 to 1000, but it pops from recent blocks like below which is not included in the range.

```
2018-06-25 02:13:54.755	    7f1d37e8b780	INFO 	global	src/cryptonote_core/blockchain.cpp:460	Current top block <349d8a4aa117a00c69d8b9b63772d18421ca55e91d0097868c5356947d4e96e2> at height 1131410 has version 8 which disagrees with the ideal version 2
2018-06-25 02:13:54.756	    7f1d37e8b780	INFO 	global	src/cryptonote_core/blockchain.cpp:462	Popping blocks... 1131410
2018-06-25 02:13:54.994	    7f1d37e8b780	INFO 	global	src/cryptonote_core/blockchain.cpp:462	Popping blocks... 1131310
...
```

And after it passes 1130000 which I specified as a starting block, it continues! And if I stop the sequences, the blocks read are broken. So, I must re-sync the block.

```
...
2018-06-25 02:14:17.414	    7f1d37e8b780	INFO 	global	src/cryptonote_core/blockchain.cpp:462	Popping blocks... 1122410
2018-06-25 02:14:17.690	    7f1d37e8b780	INFO 	global	src/cryptonote_core/blockchain.cpp:462	Popping blocks... 1122310
^C
```

and monerod using --testnet flag emits

```
2018-06-25 02:17:23.102	[P2P4]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:310	[176.9.89.217:28080 OUT] Sync data returned a new top block candidate: 1122241 -> 1131413 [Your node is 9172 blocks (12 days) behind]
SYNCHRONIZATION started
2018-06-25 02:17:26.392	[P2P3]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1171	[176.9.89.217:28080 OUT]  Synced 1122261/1131413
2018-06-25 02:17:27.579	[P2P6]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1171	[176.9.89.217:28080 OUT]  Synced 1122281/1131413
```

It re-sync again after the block I stopped! Does this program not working on Monero testnet?

**Comment by stoffu** [comment]
The block version at height 1131410 is v2 on mainnet and v8 on testnet:

- https://github.com/monero-project/monero/blob/ffab67004ca9a846d6f6d39de552e7ce79febf88/src/cryptonote_core/blockchain.cpp#L95

- https://github.com/monero-project/monero/blob/ffab67004ca9a846d6f6d39de552e7ce79febf88/src/cryptonote_core/blockchain.cpp#L134

So it seems like the code initializes the hard fork info always with the mainnet even when the testnet flag is specified.

**Comment by heojae91** [comment]
So, how could it be solved on testnet? I should wait till the fix? Or, is there any way I can do to fix the problem on my local blocks?

**Comment by moneroexamples** [comment]
I though I fixed it before, but let me double check it.

EDIT: Oh. not fixed. Probably fixed that for other example. I will fix it soon.

**Comment by moneroexamples** [comment]
Fixed. Have a look now

Also if you use command `./xmr2csv -t 1130000 -n 1000 --all-outputs --testnet`  you will need to provide some testnet address, just for the sake of it being there:

e.g.

```
./xmr2csv -t 1120000 -n 1000 --all-outputs --testnet -a 9viPdjLNXDaRFNtTTDg5wXg9Yg55uDC9XRLv882aPAFye1Ta6fSh25M41JoXBQj8d964JyFXuLVddEdg71cPJ8DY7WrSH3z
```

**Comment by heojae91** [comment]
Wow, it worked! I really appreciate it!

**Comment by moneroexamples** [comment]
No problem. If something else, please let me know.

**Comment by heojae91** [comment]
Another problem here. I tried on main net using example of Forum Donation and it nicely generates output. But, in testnet, I cannot get the correct value. I used :  `./xmr2csv -t 01131509 -m -n 1 -a <<address>> -v <<private viewkey>> --testnet` to get my ring members, but it generates the error.

```
Unsupported rct type:
Cant decode ringCT!
terminate called after throwing an instance of 'std::runtime_error'
  what():  Cant decode ringCT!
Aborted (core dumped)
```

What could be the problem?

**Comment by moneroexamples** [comment]
Cant replicate this issues. Seems to be working fine for me. Which monero version do you use? Latest development from master branch of monero, or officially released v0.12.2.0?

**Comment by heojae91** [comment]
I'm using v0.12.2.0 now. xmr2csv on the blocks which doesn't have my transaction are nicely working, but if there is transaction of mine, it stopped working. Additionally, I tried all-outputs flag with my address to get every output, every Tx_version in the .csv file has value of 2. Does it alright?

**Comment by moneroexamples** [comment]
**Tx_version** of 2 is fine. It means that this tx is ringct. You can check tx version in testnet blockchain explorer: https://testnet.xmrchain.com/tx/9a3c212a28d69963970b3277afd366154c131f25b1af35de6419be3f426a107c

ringct deconding could be failing because on testnet, booletproof txs are already used. I will check with  v0.12.2.0, as I used the latest development version of monero, and will report back soon.

**Comment by moneroexamples** [comment]
Also which Linux do you use?

p.s. To check on monero v0.12.2.0 I have to resyc-testnet, as its database format changed. So its resyncing now, but it will take some time till finish.

**Comment by heojae91** [comment]
I'm using Ubuntu 16.04.4 LTS.

**Comment by moneroexamples** [comment]
Its still syncing. In the mean time, would you mind sharing your testnet address and viewkey? This way I could hopefully quickly reproduce your error and identify which tx fails and why?

**Comment by heojae91** [comment]
Sure. My address is `9wPGoMe35nNGt8C6Gn1Fzq3CvmyPjYRbJAcadMjSqHjMXPCX2puas98DHNJbkmi8wUVFzoKRCgJ8zGenHTrf5HnYBto6YyP` and view key is `eb449e4e257c36718301cdbe3f9b08f05d718527882c334b26baa6391a85eb0b`

**Comment by moneroexamples** [comment]
Thanks. It works for me, but I use latest monero development version. To test on v0.12.2.0 I still wait for resync to complete.

But, I patched the program so that it does not abort when this problem occurs. Instead it prints out a message that it cant decode ringct and gives tx hash for a tx that causes it. In that case, tx is skipped and tx hash can be used to inspect said tx in testnet explorer.

Have you considered using stagenet instead of testnet? stagenet is meant to be comtabile with mainnet. Testnet is more like a develnet, where all the latest monero futures goes first, thus it breaks more often than not.

**Comment by heojae91** [comment]
Okay, thank you for explain the way that I can do. I'll try on stagenet instead of testnet.
