### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by SofieC93** [moneroexamples/transactions-export#18]
Hi,
I'm trying to compile transactions-export, but keep getting the same error. I'm following the instructions as they are written on the github page, but when I get to the final stage and run make, I get this error.
Any help would be greatly appreciated,
Thanks
![make error](https://user-images.githubusercontent.com/26059619/44518303-d2c7ab80-a6c1-11e8-9810-8fb26e9e7189.JPG)

**Comment by moneroexamples** [comment]
do you use latest monero master branch?

**Comment by edenweb1** [comment]
same problem here. i used monero release-v0.15 branch

**Comment by MyCryptoCheckout** [comment]
When compiling monero, do this:

```
# Use a single build dir for Monero, else the transactions export doesn't compile.
USE_SINGLE_BUILDDIR=1 make

```

**Comment by moneroexamples** [comment]
I updated transactions-export to compile with latest monero's `master` branch. Can you check?

**Comment by edenweb1** [comment]
> I updated transactions-export to compile with latest monero's `master` branch. Can you check?

Thank you VM, It work now :)
