### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by shunryokan** [moneroexamples/transactions-export#19]
I'm getting a Floating point exception (core dumped) while trying out the Examples.

**Comment by moneroexamples** [comment]
Could you provide more info. Which example, what os and monero version?

**Comment by shunryokan** [comment]
I compiled everything using Ubuntu 18.04 running on a VMWare 15 Player VM. Don't know which Monero version.

The first problem i got was while trying out this part:
"Getting our outputs using address and viewkey

For testing of the viewer, one can use official address and viewkey of the Monero, i.e.,

Address: 44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A
    Viewkey: f359631075708155cc3d92a32b75a7d02a5dcf27756707b47a2b31b21c389501"

**Comment by moneroexamples** [comment]
Does it produce any error messages before crashing? Does it crash at random places, or always to some specific block/tx?

I've just run the example, and it seems all good. So you need to be more specific, for me to be able to help. Maybe you can run it through debugger `gdb` and provide information from there about the crash?
