### ISSUE TITLE
Seeing spent funds in 'view_key only' mode

### ISSUE THREAD

**Issue by pmitchev** [moneroexamples/transactions-export#2]
Is there a way to track spent key_images in 'view_key only' mode? I see MyMonero does it somehow, I don't understand how

**Comment by moneroexamples** [comment]
Its not possible to generate a key_image without spendkey. So it cant be done with viewkey only. Mymonero does it by storing your key_images on their server, which you generate for them in your browser using your spendkey. And they only have access to spent key_images.

Please let me know if you have any more questions or suggestions for the transactions-export tool.

**Comment by pmitchev** [comment]
This is actually a very helpful reply. Please keep this issue open if someone else struggle with the same problem

**Comment by moneroexamples** [comment]
Thanks. No problem.
