### ISSUE TITLE
error: no matching function for call to ‘cryptonote::BlockchainDB::get_output_key

### ISSUE THREAD

**Issue by MyCryptoCheckout** [moneroexamples/transactions-export#20]
After compiling the latest Monero in ~/monero, git log below:

`commit 9547e3f4513ca15bfbb52eb871e0a14e905d4949 (HEAD -> master, origin/master, origin/HEAD)
Merge: de6d6c0e 807903bb
Author: Riccardo Spagni <ric@spagni.net>
Date:   Mon Mar 4 17:17:34 2019 +0200
`

Compiling trans export fails.

> > [ 92%] Building CXX object CMakeFiles/xmr2csv.dir/main.cpp.o
> /home/xxx/transactions-export/main.cpp: In function ‘int main(int, const char**)’:
> /home/xxx/transactions-export/main.cpp:561:72: error: no matching function for call to ‘cryptonote::BlockchainDB::get_output_key(uint64_t&, std::vector<long unsigned int, std::allocator<long unsigned int> >&, std::vector<cryptonote::output_data_t>&)’
>                                                            mixin_outputs);
>                                                                         ^
> In file included from /home/xxx/monero/src/cryptonote_core/tx_pool.h:46:0,
>                  from /home/xxx/transactions-export/src/monero_headers.h:27,
>                  from /home/xxx/transactions-export/src/MicroCore.h:10,
>                  from /home/xxx/transactions-export/main.cpp:1:
> /home/xxx/monero/src/blockchain_db/blockchain_db.h:1313:25: note: candidate: virtual cryptonote::output_data_t cryptonote::BlockchainDB::get_output_key(const uint64_t&, const uint64_t&, bool) const
>    virtual output_data_t get_output_key(const uint64_t& amount, const uint64_t& index, bool include_commitmemt = true) const = 0;
>                          ^~~~~~~~~~~~~~
> /home/xxx/monero/src/blockchain_db/blockchain_db.h:1313:25: note:   no known conversion for argument 2 from ‘std::vector<long unsigned int, std::allocator<long unsigned int> >’ to ‘const uint64_t& {aka const long unsigned int&}’
> /home/xxx/monero/src/blockchain_db/blockchain_db.h:1365:16: note: candidate: virtual void cryptonote::BlockchainDB::get_output_key(const epee::span<const long unsigned int>&, const std::vector<long unsigned int, std::allocator<long unsigned int> >&, std::vector<cryptonote::output_data_t>&, bool) const
>    virtual void get_output_key(const epee::span<const uint64_t> &amounts, const std::vector<uint64_t> &offsets, std::vector<output_data_t> &outputs, bool allow_partial = false) const = 0;
>                 ^~~~~~~~~~~~~~
> /home/xxx/monero/src/blockchain_db/blockchain_db.h:1365:16: note:   no known conversion for argument 1 from ‘uint64_t {aka long unsigned int}’ to ‘const epee::span<const long unsigned int>&’
> CMakeFiles/xmr2csv.dir/build.make:62: recipe for target 'CMakeFiles/xmr2csv.dir/main.cpp.o' failed
> make[2]: *** [CMakeFiles/xmr2csv.dir/main.cpp.o] Error 1
> CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/xmr2csv.dir/all' failed
> make[1]: *** [CMakeFiles/xmr2csv.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by moneroexamples** [comment]
Do you use `release-v0.13` of monero? The transaction-export will not compile with `master` branch of monero. In readme you can find how to checkout `release-v0.13` of monero in case you are not sure: https://github.com/moneroexamples/transactions-export#compile-latest-monero

**Comment by MyCryptoCheckout** [comment]
Compiling it with 13 works just fine, but it's the latest monero master that I need to use, since it is going to be hard forked soon.

**Comment by moneroexamples** [comment]
>  it is going to be hard forked soon

Yes. Monero branch `release-v0.13` is the fork branch and the upcoming version v.0.14.0.1. The naming is confusing, but this is how it is.

**Comment by MyCryptoCheckout** [comment]
So I tried first going to monero and

> git checkout v0.14.0.0
> git pull origin release-v0.13
> make

Make completes just fine. Then go to transactions export:

> cd build
> cmake ..
> make

Results in

> [ 57%] Building CXX object CMakeFiles/xmr2csv.dir/main.cpp.o
/home/monero/transactions-export/main.cpp: In function �int main(int, const char**)�:
/home/monero/transactions-export/main.cpp:561:72: error: no matching function for call to �cryptonote::BlockchainDB::get_output_key(epee::span<const long unsigned int>, std::vector<long unsigned int>&, std::vector<cryptonote::output_data_t>&)�
                                                           mixin_outputs);

**Comment by moneroexamples** [comment]
To build monero need to use `USE_SINGLE_BUILDDIR=1` flag, i.e., `USE_SINGLE_BUILDDIR=1 make`. 

But anyway, if you see this error about `get_output_key(epee::span` it means that you are still on `master` branch of monero. You incorrectly checked out `release-v0.13` of monero and/or compiled it.

If you are on master you can checkout the branch as follows `git checkout --track origin/release-v0.13` and compile it using `USE_SINGLE_BUILDDIR=1` flag.

Please note that current release-v0.13 branch of monero has bug and it wont compile. You need to apply patch https://github.com/monero-project/monero/pull/5242 manually or wait till it gets merged. 

I also updated the `export-transaction` with minor fixes, so you can also pull the latest changes.

**Comment by MyCryptoCheckout** [comment]
Ok. I believe the biggest problem was the `USE_SINGLE_BUILDDIR=1` flag.

After checkout out 14.0.2 and single building, and then building the exporter, things seem to be working again.

Thanks for the help!
