### ISSUE TITLE
undefined reference to `monero_crypto_amd64_64_24k_generate_subaddress_public_ke

### ISSUE THREAD

**Issue by MyCryptoCheckout** [moneroexamples/transactions-export#21]
Getting a compilation error with the latest Monero.

#~/monero$ git branch
* (HEAD detached at v0.17.1.3)

Scanning dependencies of target myxrm
[  8%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
[ 16%] Building CXX object src/CMakeFiles/myxrm.dir/tools.cpp.o
[ 25%] Building CXX object src/CMakeFiles/myxrm.dir/CmdLineOptions.cpp.o
[ 33%] Building CXX object src/CMakeFiles/myxrm.dir/tx_details.cpp.o
[ 41%] Linking CXX static library libmyxrm.a
[ 41%] Built target myxrm
[ 50%] Building CXX object ext/CMakeFiles/myext.dir/dateparser.cpp.o
[ 58%] Linking CXX static library libmyext.a
[ 58%] Built target myext
Scanning dependencies of target xmr2csv
[ 66%] Building CXX object CMakeFiles/xmr2csv.dir/main.cpp.o
[ 75%] Linking CXX executable xmr2csv
/home/monero/monero/build/release/src/device/libdevice.a(device_default.cpp.o): In function `hw::core::device_default::derive_subaddress_public_key(crypto::public_key const&, crypto::key_derivation const&, unsigned long, crypto::public_key&)':
device_default.cpp:(.text+0x106): undefined reference to `monero_crypto_amd64_64_24k_generate_subaddress_public_key'
/home/monero/monero/build/release/src/device/libdevice.a(device_default.cpp.o): In function `hw::core::device_default::generate_key_derivation(crypto::public_key const&, epee::mlocked<tools::scrubbed<crypto::ec_scalar> > const&, crypto::key_derivation&) [clone .localalias.350]':
device_default.cpp:(.text+0x258): undefined reference to `monero_crypto_amd64_64_24k_generate_key_derivation'
/home/monero/monero/build/release/src/device/libdevice.a(device_default.cpp.o): In function `hw::core::device_default::encrypt_payment_id(crypto::hash8&, crypto::public_key const&, epee::mlocked<tools::scrubbed<crypto::ec_scalar> > const&)':
device_default.cpp:(.text+0x741): undefined reference to `monero_crypto_amd64_64_24k_generate_key_derivation'
/home/monero/monero/build/release/src/device/libdevice.a(device_default.cpp.o): In function `hw::core::device_default::generate_output_ephemeral_keys(unsigned long, cryptonote::account_keys const&, crypto::public_key const&, epee::mlocked<tools::scrubbed<crypto::ec_scalar> > const&, cryptonote::tx_destination_entry const&, boost::optional<cryptonote::account_public_address> const&, unsigned long, bool const&, std::vector<epee::mlocked<tools::scrubbed<crypto::ec_scalar> >, std::allocator<epee::mlocked<tools::scrubbed<crypto::ec_scalar> > > > const&, std::vector<crypto::public_key, std::allocator<crypto::public_key> >&, std::vector<rct::key, std::allocator<rct::key> >&, crypto::public_key&)':
device_default.cpp:(.text+0x5ad4): undefined reference to `monero_crypto_amd64_64_24k_generate_key_derivation'
device_default.cpp:(.text+0x5c0a): undefined reference to `monero_crypto_amd64_64_24k_generate_key_derivation'
collect2: error: ld returned 1 exit status
CMakeFiles/xmr2csv.dir/build.make:134: recipe for target 'xmr2csv' failed
make[2]: *** [xmr2csv] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/xmr2csv.dir/all' failed
make[1]: *** [CMakeFiles/xmr2csv.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by moneroexamples** [comment]
Thanks. Will look into it.

**Comment by moneroexamples** [comment]
You can check now. I pushed a fix to the complication error.

**Comment by MyCryptoCheckout** [comment]
It now compiles! That's fast work.

Seems to work, too!
