### ISSUE TITLE
Seg Fault

### ISSUE THREAD

**Issue by ACK-J** [moneroexamples/transactions-export#23]
After compiling xmr2csv and running `./xmr2csv -a 44AFFq5kSiGBoZ4NMDwYtN18obc8AemS33DBLWs3H7otXft3XjrpDtQGv7SqSsaBYBb98uNbr2VBBEt7f2wfn3RVGQBEP3A -v f359631075708155cc3d92a32b75a7d02a5dcf27756707b47a2b31b21c389501 -c ./current.csv`

Segmentation Fault
```
Analysing block 00063000/00063777 - date 2014-05-30 10:35:04

Csv saved as: ./current.csv

End of program.
Segmentation fault (core dumped)
```

Reading the resulting  current.csv 

```
Timestamp,Block_no,Tx_hash,Tx_public_key,Tx_version,Payment_id,Out_idx,Amount,Output_pub_key,Output_key_img,Output_spend
```

Theres no data only the heading

**Comment by moneroexamples** [comment]
Are you confident that there are any transactions in the period you scanned. `00063777` seems as you have only a fraction of the blockchain?

**Comment by ACK-J** [comment]
Ahhh good point. I overlooked that
