### ISSUE TITLE
Missing 60% of Transactions

### ISSUE THREAD

**Issue by ACK-J** [moneroexamples/transactions-export#25]
After exporting a wallets transactions using `xmr2csv` and also exporting the same wallet's transactions using `export_transfers all` inside the `monero-wallet-cli` there is a large discrepency in the amount of transactions outputed. 
```
# The output of the Monero cli
ack@dev:~/Desktop$ cat output0.csv | wc -l
1416

# The output of xmr2csv
ack@dev:~/Desktop$ cat xmr_report.csv | wc -l
478
```

The command I am using to generate the output is `xmr2csv --address <addr> --viewkey <viewkey> --spendkey <spendkey> --start-height 1908344 --testnet --ring-members`

**Comment by moneroexamples** [comment]
Any txs into sub-addresses will not be accounted for. You have to search for sub-addresses separately. 

p.s.

This is one of the features I plan to add (automatic inclusion of sub-addresses).

**Comment by ACK-J** [comment]
That makes sense! Is there any hacky workaround I could do to make it work for sub addresses or should I just wait for it to be implemented?

**Comment by moneroexamples** [comment]
Sadly there is no "hack". If you know sub-addresses you have to manually search using them instead of original ones.

At the moment I don't have a time frame when automated search for sub-addresses belonging to a given address will be implemented.

**Comment by ACK-J** [comment]
So if I use the subaddress instead of the main address and keep the same private viewkey and private spendkey, xmr2csv will grab all the transactions for that subaddress?

**Comment by moneroexamples** [comment]
It should. It does not work?

**Comment by ACK-J** [comment]
It does work. For anyone facing the same issue you can use the following command to extract all the used subaddresses in a Monero wallet.

`curl http://127.0.0.1:18082/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_address","params":{"account_index":0,}' -H 'Content-Type: application/json' -s | jq -r '.result.addresses[]|select(.used == true)| .address'`

You can then pipe the output to `xargs` and have xmr2csv extract the transaction information for each subaddress.
