### ISSUE TITLE
Question: xmr_report.csv Out_idx attribute

### ISSUE THREAD

**Issue by ACK-J** [moneroexamples/transactions-export#28]
The columns output for the xmr_report file are:
`Timestamp,Block_no,Tx_hash,Tx_public_key,Tx_version,Payment_id,Out_idx,Amount,Output_pub_key,Output_key_img,Output_spend`
I am trying to figure out what `Out_idx` is because from what I can tell it is a binary value that represents if a transaction is "outgoing" or "incoming" but the name makes it sound like it represents the output index in a users wallet.

https://github.com/moneroexamples/transactions-export/blob/e7fde6c474310f5e2396aaa0903b5630a73c0155/main.cpp#L440-L444

Right now my script has a bug where some "incoming" transactions are in the dataset. I tracked down one example shown below.
### xmr_report.csv
```
Timestamp,Block_no,Tx_hash,Tx_public_key,Tx_version,Payment_id,Out_idx,Amount,Output_pub_key,Output_key_img,Output_spend
2022-02-11 21:48:46,1915943,af5d49d3d81d16d8591033d1e01a4b120729223791d6416c674014965dc9a0d8,3edb58f40cefd4c55a9aa3ac5357b1853a45ca6c2842fd69b45a5c695e0040d4,2,0000000000000000000000000000000000000000000000000000000000000000,1,350000000000,12de70643868471b6ed2afba5ae6de122a1843fd64688d54375e2189ba26f598,0518788ca40d865a008f39c37c5268cc99b37ab205bf3c5e2ebd887664c195e0,1
```
### monero wallet cli export.csv
```
block, direction, unlocked, timestamp, amount, running balance, hash, payment ID, fee, destination, amount, index, note
1915943, in, unlocked, 2022-02-11 21:48:46, 0.350000000000, 0.350000000000,af5d49d3d81d16d8591033d1e01a4b120729223791d6416c674014965dc9a0d8, 0000000000000000, 0.000000000000, 9snkJksfGfxNath4ZxLJ7N5hHWS9BAg2hXNyqxvSKpUwMfo2Bm2X7Qm5Z4EjwxbypQ6uzFFuu79UeHsPwn1vYfWMKESsT2a, 0.350000000000, "0",
```

Notably the above two transaction hashes are the same and the monero wallet cli indicates that it is an "in" (incoming) transaction. If I could get a confirmation that `Out_idx` is a binary value that represents "in" and "out" transactions, that would be awesome.

**Comment by moneroexamples** [comment]
`Out_idx` is not related to tx being incoming or outgoing. Instead it denotes a position on the list of outputs in a txs. These days there are only two outputs in a tx, but before a tx could have many outputs.

**Comment by ACK-J** [comment]
@moneroexamples Okay that makes more sense. But to clarify, the position represents the output spent to the recipient address and does not represent the "change" sent back to the senders wallet?

**Comment by moneroexamples** [comment]
@ACK-J  

It is incoming xmr, which will be a change when you make an outgoing txs. `xmr2csv` does not recognize outgoing txs in the same way as the wallet does.
