### ISSUE TITLE
Outputs Skipped From Finding Ring Members

### ISSUE THREAD

**Issue by ACK-J** [moneroexamples/transactions-export#29]
Once processing the data exported from xmr2csv I noticed that only one output was ever being searched across the chain to find where it has been used within other ring signatures. Notice that in the image below `6cf9facc7471290473ee4c5002af1ab345573392c745fad8c412d313ac1891a1` is never referenced in `Decoys_On-Chain`. My question is looking at the documentation there is a flag named `--all-outputs` would adding this fix the issue I am seeing?
![image](https://user-images.githubusercontent.com/60232273/160889888-a7710c93-3098-48e4-893a-bca3e3f30b6a.png)

**Comment by moneroexamples** [comment]
Would you be able to provide example of that? For example using testnet or stagenet wallet that allowed me to reproduce the issue?

**Comment by ACK-J** [comment]
I'm not sure if this is related but after running:

```
xmr2csv --address 9shjquoB4e4HBNzvAKbUdHMBn3TohvdTibcyULLinL4mFvZ9sMp69fqBRFXFGfiiudKwk9ShTAHEFDJNaRTkAYeoQc1fhq5 --viewkey 6aa7f93f18625d79499c68e724b18b40dd1e88fec7062a3f0245cef42e2cb100 --spendkey e516fcc9b2d211622ec6bb240d8b1bbc47374d888ddaccf8b7c9c15c2ebeb407 --testnet --start-height 1910710 --ring-members --out-csv-file ./xmr_report_9shjquoB4e4HBNzvAKbUdHMBn3TohvdTibcyULLinL4mFvZ9sMp69fqBRFXFGfiiudKwk9ShTAHEFDJNaRTkAYeoQc1fhq5.csv --out-csv-file2 ./xmr_report_ring_members_9shjquoB4e4HBNzvAKbUdHMBn3TohvdTibcyULLinL4mFvZ9sMp69fqBRFXFGfiiudKwk9ShTAHEFDJNaRTkAYeoQc1fhq5.csv --out-csv-file3 ./xmr_report_ring_members_freq_9shjquoB4e4HBNzvAKbUdHMBn3TohvdTibcyULLinL4mFvZ9sMp69fqBRFXFGfiiudKwk9ShTAHEFDJNaRTkAYeoQc1fhq5.csv --out-csv-file4 ./xmr_report_key_images_outputs_9shjquoB4e4HBNzvAKbUdHMBn3TohvdTibcyULLinL4mFvZ9sMp69fqBRFXFGfiiudKwk9ShTAHEFDJNaRTkAYeoQc1fhq5.csv --out-csv-file5 ./xmr_report_outgoing_txs_9shjquoB4e4HBNzvAKbUdHMBn3TohvdTibcyULLinL4mFvZ9sMp69fqBRFXFGfiiudKwk9ShTAHEFDJNaRTkAYeoQc1fhq5.csv
```
`xmr_report.csv` has the transaction hash `e55582baba22d8546d30a7ec83568d7d18759622f7729f226801afa821418775` as the first transaction
```
Timestamp | Block_no | Tx_hash | Tx_public_key | Tx_version | Payment_id | Out_idx | Amount | Output_pub_key | Output_key_img | Output_spend
2022-02-03 21:58:19 | 1910711 | e55582baba22d8546d30a7ec83568d7d18759622f7729f226801afa821418775 | dd43b82b4c6dc8d998f7e5718e7f421ce9eab2f6344318af6860f50832cf72b7 | 2 | 0 | 0 | 949983869999 | 76b282d9953024ac7af10f7fb1fe587117b198adc704fce737bff11f01648730 | 2d42b3a9ee439fd0c6b49dae8479d49d5e92dea3ddc707943c34f209ef459fb8 | 1
```

Using the `monero-wallet-cli` native export function you can verify that `e55582baba22d8546d30a7ec83568d7d18759622f7729f226801afa821418775` is an `outgoing` transaction

```
block | direction | unlocked | timestamp | amount | running balance | hash | payment ID | fee | destination | amount | index | note | 
1910711 | out | - | 2022-02-03 21:58:19 | 1E-12 | 18446744.0736934 | e55582baba22d8546d30a7ec83568d7d18759622f7729f226801afa821418775 | 0 | 1.613E-05 | 9sMBtKGWezhjLXmjiKAygwd9ngMduPBZXUS57JkWV5wUS7dnf6zofAwVKMfshP83JTBpMKENBZmCParAyD1yriMJ9twREdN | 1E-12 | 0 |   |  

```

However in the `xmr_report_outgoing_txs.csv` there is no reference to this transaction. I attached the file below for debugging. Additionally here is the transaction on a block explorer. https://testnet.xmrchain.net/search?value=e55582baba22d8546d30a7ec83568d7d18759622f7729f226801afa821418775

```
dev@dev:/$ grep "e55582baba22d8546d30a7ec83568d7d18759622f7729f226801afa821418775" < xmr_report_outgoing_txs.csv  | wc -l
0
```

[FILE: xmr_report_outgoing_txs.csv](https://github.com/moneroexamples/transactions-export/files/8404788/xmr_report_outgoing_txs_9shjquoB4e4HBNzvAKbUdHMBn3TohvdTibcyULLinL4mFvZ9sMp69fqBRFXFGfiiudKwk9ShTAHEFDJNaRTkAYeoQc1fhq5.csv)

[FILE: monero_wallet_cli_export.csv](https://github.com/moneroexamples/transactions-export/files/8404990/cli_export_9shjquoB4e4HBNzvAKbUdHMBn3TohvdTibcyULLinL4mFvZ9sMp69fqBRFXFGfiiudKwk9ShTAHEFDJNaRTkAYeoQc1fhq5.csv)

**Comment by moneroexamples** [comment]
Thanks. I will have a look

**Comment by moneroexamples** [comment]
This happens because the output spent in the tx `e55582baba22d8546d30a7ec83568d7d18759622f7729f226801afa821418775` is older then  `1910710` (you start scanning the blockchain from that height). 

`xmr2csv` is not retrospective. It will not be aware of any outputs older then `--start-height 1910710`. To overcome that you have to start scanning earlier if you want to account for all outputs. 

Usually you would start scanning from the time your wallet was created. This seems to be block `1908702`.

**Comment by ACK-J** [comment]
@moneroexamples that makes a lot of sense. Thanks again!
