### ISSUE TITLE
Error when trying to compile...

### ISSUE THREAD

**Issue by slabon** [moneroexamples/transactions-export#3]
I did compile monero, installed librairies & headers as required... but it seem I'm mising something...?

pool@pool:~/transactions-export$ make
Scanning dependencies of target myxrm
[ 10%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
In file included from /home/pool/transactions-export/src/MicroCore.h:10:0,
                 from /home/pool/transactions-export/src/MicroCore.cpp:5:
/home/pool/transactions-export/src/monero_headers.h:18:46: fatal error: cryptonote_core/cryptonote_basic.h: No such file or directory
compilation terminated.
src/CMakeFiles/myxrm.dir/build.make:62: recipe for target 'src/CMakeFiles/myxrm.dir/MicroCore.cpp.o' failed
make[2]: *** [src/CMakeFiles/myxrm.dir/MicroCore.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'src/CMakeFiles/myxrm.dir/all' failed
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by moneroexamples** [comment]
Seems, it hasn't been updated to newest monero. Just fixed that.

 If something else, please dont hesitate to let me know.

**Comment by slabon** [comment]
Ok will try again now... :)
Cheers!

**Comment by slabon** [comment]
Perfect successful build!

Scanning dependencies of target myxrm
[ 10%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
[ 20%] Building CXX object src/CMakeFiles/myxrm.dir/tools.cpp.o
[ 30%] Building CXX object src/CMakeFiles/myxrm.dir/CmdLineOptions.cpp.o
[ 40%] Building CXX object src/CMakeFiles/myxrm.dir/tx_details.cpp.o
[ 50%] Linking CXX static library libmyxrm.a
[ 50%] Built target myxrm
Scanning dependencies of target myext
[ 60%] Building CXX object ext/CMakeFiles/myext.dir/format.cc.o
[ 70%] Building CXX object ext/CMakeFiles/myext.dir/dateparser.cpp.o
[ 80%] Linking CXX static library libmyext.a
[ 80%] Built target myext
Scanning dependencies of target xmr2csv
[ 90%] Building CXX object CMakeFiles/xmr2csv.dir/main.cpp.o
[100%] Linking CXX executable xmr2csv
[100%] Built target xmr2csv
