### ISSUE TITLE
boost::bad_get: failed value get using boost::get for tx: xxx Skipping this tx!

### ISSUE THREAD

**Issue by MyCryptoCheckout** [moneroexamples/transactions-export#32]
The exporter no longer reports values when asked to. Same script, same view keys and everything.

Used to work until the latest version of Monero.

Linux xxx 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

libboost-dev/oldoldstable,now 1.62.0.1 amd64 [installed,automatic]

**Comment by moneroexamples** [comment]
Do you have any more info on the issue? How to reproduce the problem?

**Comment by MyCryptoCheckout** [comment]
I tried on another machine with a brand new chain sync, brand new download of transactions export.

./xmr2csv -t 2696737 -a ADDRESSHERE -v VIEWKEY -n 1 -c temp.csv
Blockchain path: "XXX/.bitmonero/lmdb"
Start block date       : 2022-08-24 17:49:05
Start block height     : 2696737
Search for ring members: False

address          : <ADDRESSHERE>
private view key : <VIEWKEY>
private spend key: not given

boost::bad_get: failed value get using boost::get for tx: 20f180620b2df345feb0589e48a90fd7f305b15beb33ea222755ce51f556efa5 Skipping this tx!
boost::bad_get: failed value get using boost::get for tx: 13fa21e64e74e3362f10d6bb5a908b496efe3b1c0b8198922fae9490b79f2314 Skipping this tx!
boost::bad_get: failed value get using boost::get for tx: f3389e2efe2061ef4740dc4fa81979a02f7ae0bcaf9855824925d7ab9d7b3716 Skipping this tx!
boost::bad_get: failed value get using boost::get for tx: 4f380569d1b3cc50bc9e1609f1d8da241698e9a6ef05822f06999f211c9f6284 Skipping this tx!
boost::bad_get: failed value get using boost::get for tx: 13fd63d2f0d7b55baa32069addf4f8096ac30ee94290a46e8df98bac67957e6b Skipping this tx!
boost::bad_get: failed value get using boost::get for tx: 48162b1e45e09d29654f41f9cc355dc6a5daf732d72f0b39982de3c5249ea775 Skipping this tx!
boost::bad_get: failed value get using boost::get for tx: c4adf5ee85cbed322dd59230476340fab08e7ceb7732870e88364c85070e7ba3 Skipping this tx!
several more such lines

Linux XXX 5.9.0-0.bpo.5-amd64 #1 SMP Debian 5.9.15-1~bpo10+1 (2020-12-31) x86_64 GNU/Linux

libboost-all-dev/oldstable,oldstable,now 1.67.0.1 amd64

**Comment by moneroexamples** [comment]
Can you please check now. It should be fixed.
