### ISSUE TITLE
Output a gzipped CSV

### ISSUE THREAD

**Issue by mj-xmr** [moneroexamples/transactions-export#34]
Hey @moneroexamples ,

Because the output takes plenty of disk space, would you accept a PR that either:

- optionally uses Boost::iostreams to output a gzipped archive of the CSV directly, or
- optionally uses std::cout for the actual output and std::cerr for errors and messages, so that the output can be piped to `tar` (and friends)?

I have production ready code for the 1st option, if that's your preference.

**Comment by moneroexamples** [comment]
Sure, you can PR that. I will have a look. Thanks for help.
