### ISSUE TITLE
error: ‘null_hash’ is not a member of ‘cryptonote’

### ISSUE THREAD

**Issue by Cyclenerd** [moneroexamples/transactions-export#4]
Hi,

I have a fresh installation of Ubuntu 16.04.3 LTS and Monero 'Helium Hydra' (v0.11.0.0-5f7cdde).

I've used your guide. I had to install a few more packages (I'll send you a pull).

`make` unfortunately provides an error:

```
nils@cryptocurrency build $ make
Scanning dependencies of target myxrm
[ 10%] Building CXX object src/CMakeFiles/myxrm.dir/MicroCore.cpp.o
[ 20%] Building CXX object src/CMakeFiles/myxrm.dir/tools.cpp.o
[ 30%] Building CXX object src/CMakeFiles/myxrm.dir/CmdLineOptions.cpp.o
[ 40%] Building CXX object src/CMakeFiles/myxrm.dir/tx_details.cpp.o
/home/nils/moneroexamples/transactions-export/src/tx_details.cpp: In function ‘std::vector<xmreg::transfer_details> xmreg::get_belonging_outputs(const cryptonote::bl
ock&, const cryptonote::transaction&, const cryptonote::account_public_address&, const crypto::secret_key&, uint64_t)’:
/home/nils/moneroexamples/transactions-export/src/tx_details.cpp:126:26: error: ‘null_hash’ is not a member of ‘cryptonote’
             payment_id = cryptonote::null_hash;
                          ^
/home/nils/moneroexamples/transactions-export/src/tx_details.cpp:126:26: note: suggested alternatives:
In file included from /opt/monero-dev/headers/src/crypto/chacha8.h:42:0,
                 from /opt/monero-dev/headers/src/serialization/crypto.h:37,
                 from /opt/monero-dev/headers/src/cryptonote_basic/cryptonote_basic.h:45,
                 from /opt/monero-dev/headers/src/cryptonote_basic/cryptonote_basic_impl.h:33,
                 from /opt/monero-dev/headers/src/cryptonote_core/tx_pool.h:44,
                 from /home/nils/moneroexamples/transactions-export/src/monero_headers.h:19,
                 from /home/nils/moneroexamples/transactions-export/src/tx_details.h:12,
                 from /home/nils/moneroexamples/transactions-export/src/tx_details.cpp:5:
/opt/monero-dev/headers/src/crypto/hash.h:89:29: note:   ‘crypto::null_hash’
   const static crypto::hash null_hash = boost::value_initialized<crypto::hash>();
                             ^
/opt/monero-dev/headers/src/crypto/hash.h:89:29: note:   ‘crypto::null_hash’
/opt/monero-dev/headers/src/crypto/hash.h:89:29: note:   ‘crypto::null_hash’
/home/nils/moneroexamples/transactions-export/src/tx_details.cpp: In function ‘std::vector<xmreg::transfer_details> xmreg::get_outputs(const cryptonote::block&, const cryptonote::transaction&, uint64_t)’:
/home/nils/moneroexamples/transactions-export/src/tx_details.cpp:252:26: error: ‘null_hash’ is not a member of ‘cryptonote’
             payment_id = cryptonote::null_hash;
                          ^
/home/nils/moneroexamples/transactions-export/src/tx_details.cpp:252:26: note: suggested alternatives:
In file included from /opt/monero-dev/headers/src/crypto/chacha8.h:42:0,
                 from /opt/monero-dev/headers/src/serialization/crypto.h:37,
                 from /opt/monero-dev/headers/src/cryptonote_basic/cryptonote_basic.h:45,
                 from /opt/monero-dev/headers/src/cryptonote_basic/cryptonote_basic_impl.h:33,
                 from /opt/monero-dev/headers/src/cryptonote_core/tx_pool.h:44,
                 from /home/nils/moneroexamples/transactions-export/src/monero_headers.h:19,
                 from /home/nils/moneroexamples/transactions-export/src/tx_details.h:12,
                 from /home/nils/moneroexamples/transactions-export/src/tx_details.cpp:5:
/opt/monero-dev/headers/src/crypto/hash.h:89:29: note:   ‘crypto::null_hash’
   const static crypto::hash null_hash = boost::value_initialized<crypto::hash>();
                             ^
/opt/monero-dev/headers/src/crypto/hash.h:89:29: note:   ‘crypto::null_hash’
/opt/monero-dev/headers/src/crypto/hash.h:89:29: note:   ‘crypto::null_hash’
src/CMakeFiles/myxrm.dir/build.make:134: recipe for target 'src/CMakeFiles/myxrm.dir/tx_details.cpp.o' failed
make[2]: *** [src/CMakeFiles/myxrm.dir/tx_details.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'src/CMakeFiles/myxrm.dir/all' failed
make[1]: *** [src/CMakeFiles/myxrm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Has something changed here, or am I doing something wrong?

Best Regards
Nils

**Comment by moneroexamples** [comment]
You are not doing anything wrong. Its that `transactions-export` hasn't seen update in a while, as most my time goes towards `onion explorer` and `open monero`. But give me some time, I will try to make `transactions-export` work with the current monero 0.11

**Comment by moneroexamples** [comment]
I made it compile with latest monero. readme has been updated as there are new compilation instructions.

Currently, the `transactions-export` does not support RingCT txs. To add support for RingCT, I need more time. But If you want just a list of your txs from you wallet, you can use  `show_transfers` command in `monero-wallet-cli`.

**Comment by Cyclenerd** [comment]
Thank you for the fast answer. Works now.

I'm not a long time with Monero and I am looking for a simple way to read transactions from multiple addresses and viewkeys. Your program seems to be perfect for that. Maybe you have a tip. A further development would be perfect, of course.

`monero-wallet-cli`and `monero-wallet-rpc` are somewhat more complicated. `monero-wallet-rpc` might work, but here bothers me the creation of extra view only wallets.

Background: I want to save the incoming payments. Based on this I would like to build an payment gateway compatible with the BitPay API. This allows you to easy customize the many existing BitPay libraries for e-commerce shops and simply accept Monero payments.

**Comment by moneroexamples** [comment]
Thanks. So I will update it to work with RingCT. At the monent it will just show 0 as an amount for RingCT txs.

But regarding your aim, I dont think `transactions-export` would be best solution for that, if I understand correctly. I also dont know BitPay API, so can ignore my further comments, if they dont make sense. 

But maybe what  you want, could be build based on [open monero](https://github.com/moneroexamples/openmonero). You setup your own open monero backend, modified to your liking, create view only wallets for your merchants there, and then make custom front-end widgets or something for websites which query the backend using json rest api for incoming transactions?

Other  possibility could be based on kasisto project: https://www.reddit.com/r/Monero/comments/5xpl6q/kasisto_get_paid_in_xmr_testnet_demo/

There are also monero blockchain exploeres, e.g., https://xmrchain.net/ or https://moneroexplorer.com/, or you could run one youself, which have an api for checking incoming transactions in recent blocks and mempool: https://github.com/moneroexamples/onion-monero-blockchain-explorer#apioutputsblocks

Finally, there is also https://globee.com/, but its closed source I think. But maybe some parts of it are, or will, be open sourced, so you can look for foundations there.

**Comment by Cyclenerd** [comment]
Many Thanks. You can close this issue.

Maybe you're right and open monero is more suitable.

My intention you have understood correctly. It is supposed to be something like GloBee, but open source and with your own wallet. I have already looked at Kasistro. Is more for shops.

Thanks again.

**Comment by moneroexamples** [comment]
No problem. I will close the issue now. If any other questions, please feel free to ask.

**Comment by moneroexamples** [comment]
Just in case, I made to work with RingCT txs.
